### ISSUE TITLE
Failed Tweets?

### ISSUE THREAD

**Issue by QuirkyCode** [Idnan/tweet-cli#1]
Hi @Idnan Really love this, but I've noticed if the tweet is not successful it still says that it was tweeted. Is there anyway you could add something to show whether it actually managed to tweet or whether it failed or not? Or could you suggest how I could add it? 

Many thanks

@QuirkyCode.

**Comment by Idnan** [comment]
@QuirkyCode thanks for reporting. I will fix it.

**Comment by Idnan** [comment]
@QuirkyCode fixed.
